{{- if .Values.certManager.enabled -}}
---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kustomize-mutating-webhook.fullname" . }}-ca
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kustomize-mutating-webhook.fullname" . }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
spec:
  secretName: {{ include "kustomize-mutating-webhook.fullname" . }}-ca
  duration: 43800h # 5y
  issuerRef:
    name: {{ include "kustomize-mutating-webhook.fullname" . }}-ca
    kind: Issuer
  commonName: "ca.kustomize-mutating-webhook.cert-manager"
  isCA: true
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kustomize-mutating-webhook.fullname" . }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "kustomize-mutating-webhook.fullname" . }}-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kustomize-mutating-webhook.fullname" . }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "kustomize-mutating-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kustomize-mutating-webhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "kustomize-mutating-webhook.fullname" . }}
    kind: Issuer
  secretName: {{ include "kustomize-mutating-webhook.fullname" . }}-tls
  duration: {{ .Values.certManager.certificateDuration | default "2160h" }}
  renewBefore: {{ .Values.certManager.certificateRenewBefore | default "360h" }}
{{- end }}
